#include <stdio.h>
/**Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89. By considering the terms in the Fibonacci sequence whose values do not exceed 4,000,000, write a program that finds and prints the sum of the even-valued terms, followed by a new line.
 * 
 *
 *
 * Author: Taofeek Abdulrokeeb A.
 * School: Winmingle Community
 *
 */
int main (void) 
{
	unsigned long a = 1;
	unsigned long b = 2;
	unsigned long next;
	unsigned long sum = 0;

	while ( b <= 4000000) {

		if (b % 2 == 0)
		{
			sum += b;
		}

			next = a + b;
			a = b;
			b = next;
				}

			printf("%lu\n", sum);

			return 0;
}

